version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@material-ui/styles"
    versions:
    - 5.0.0-alpha.26
    - 5.0.0-alpha.28
    - 5.0.0-alpha.29
    - 5.0.0-alpha.30
    - 5.0.0-alpha.31
  - dependency-name: "@material-ui/core"
    versions:
    - 5.0.0-alpha.26
    - 5.0.0-alpha.28
    - 5.0.0-alpha.29
    - 5.0.0-alpha.30
    - 5.0.0-alpha.31
  - dependency-name: cssnano
    versions:
    - 5.0.0
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
  - dependency-name: "@next/mdx"
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
