language: node_js
node_js:
  - "stable"

script:
  - npm run build
  - npm run export

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  on:
    branch: master
