language: node_js
node_js:
  - "stable"

script:
  - 'cd layout && npm install && cd ..'
  - npm run build
  - npm run export

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: http://u-wave.net
  keep-history: true
  local-dir: out
  target-branch: master
  on:
    branch: source
